on: push
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3.0.0
      - name: 'Build'
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          PAGES_BRANCH: main
          # BUILD_DIR: docs
          TOKEN: ${{ secrets.TOKEN }}
          # BUILD_ONLY: true
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'checkout'
        uses: actions/checkout@v3.0.0
      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
      - name: 'Build and deploy'
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          PAGES_BRANCH: main
          # BUILD_DIR: docs
          TOKEN: ${{ secrets.TOKEN }}
          REPOSITORY: erg-lang/erg-lang.github.io
